{162}{362}CZ SUBTiTLES: machacek2002|{y:i}..::30/12/2002::..
{365}{500}FiNAL CORRECTiONS & SYNC|FOR SATELLiTE RELEASE BY LORD dR-aGoN
{749}{807}NÁVRAT|DO BUDOUCNOSTI
{1837}{2012}Brownovo sídlo znièené.|Brown rozprodal všechen svùj majetek,|aby mohl pokraèovat ve vızkumu.
{2158}{2205}{y:i}Øíjen je nejvhodnìjší|{y:i}dobou na investovaní
{2209}{2291}{y:i}Právì nyní poskytuje firma|{y:i}Statler Toyota nejlepší nabídku roku...
{2296}{2345}{y:i}...na všechny modely Toyota z roku 1985.
{2349}{2389}{y:i}Lepší auto prostì nenajdete...
{2393}{2480}{y:i}...s lepší cenou a lepším servisem|{y:i}nikde v Hill Valley.
{2621}{2686}{y:i}Dnes oèekáváme vısledky|{y:i}hlasovaní v senátu.
{2690}{2789}{y:i}Ještì struèná poznámka, oficiální místa|{y:i}nukleárního vızkumu...
{2797}{2866}{y:i}...popøeli zprávy ohlednì|{y:i}chybìjícího kuføíku s plutoniem, kterı...
{2870}{2936}{y:i}...mìl bıt ukraden|{y:i}z jejich trezoru pøed dvìmi tıdny.
{2942}{3029}{y:i}Skupina teroristù z Líbie|{y:i}se ke krádei sice pøihlásila...
{3035}{3150}{y:i}Pøesto povaují oficiální místa tento incident|{y:i}za obyèejnou administrativní chybu.
{3157}{3239}{y:i}FBI, které vede vyšetøování se k této|{y:i}události zatím nevyjádøilo.
{4247}{4275}Doktore?
{4341}{4367}{y:i}Doktore?
{4396}{4444}{y:i}Haló! Je nìkdo doma?
{4449}{4479}{y:i}Einsteine, pojï sem, chlapèe.
{4512}{4556}Co se to tady dìje? Boe.
{4598}{4624}{y:i}Kriste!
{4639}{4683}{y:i}To je odporné.
{6740}{6773}Rock 'n' roll.
{6970}{7013}Ano.|{y:i}- Marty, jsi to ty?
{7020}{7065}Doktore. Kde jste?
{7069}{7148}{y:i}Díky bohu, e jsem tì našel.|{y:i}Pøijï dnes v noci v jednu hodinu a patnáct minut|{y:i}k nákupnímu støedisku Two Pines.
{7154}{7211}{y:i}Udìlal jsem objev a budu|{y:i}potøebovat tvou pomoc.
{7216}{7290}V 1:15 v noci?|Doktore, o co jde?
{7295}{7342}Kde jste byli celı tıden?|{y:i}- Pracuji.
{7345}{7417}Je Einstein s vámi?|{y:i}- Ano, je právì u mnì.
{7422}{7479}Nechali jste pøístroje|celı tıden zapnuté.
{7483}{7543}{y:i}Aha, moje pøístroje.|{y:i}To mi pøipomíná, Marty.
{7548}{7637}{y:i}Nezapojuj zesilovaè.|{y:i}Je tam minimálnì monost pøetíení.
{7643}{7696}Jasnì. Budu na to myslet.
{7701}{7755}{y:i}Dobøe. Uvidíme se veèer. Nezapomeò.
{7759}{7826}{y:i}1:15 ráno,|{y:i}nákupní støedisko Two Pines...
{7990}{8095}{y:i}To co slyším jsou mé hodiny?|- Ano, právì je 8 hodin.
{8112}{8161}{y:i}Perfektní! Mùj experiment vyšel!
{8165}{8237}{y:i}Hodiny jdou pomaleji pøesnì o 25 minut!
{8250}{8307}Poèkejte chvíli, Doktore.
{8311}{8363}Chcete øíct, e je vlastnì 8:25?
{8368}{8420}{y:i}Pøesnì tak.|- Do háje!
{8444}{8488}Pøijdu pozdì do školy.
{9688}{9738}Zvolte znovu starostu|Goldie Wilsona.
{9915}{9980}- Jennifer.|- Nechoï tudy. Strickland tì u hledá.
{9985}{10046}Jestli tì chytí, bude to|tvùj ètvrtı pøestupek v øadì.
{10089}{10141}V poøádku, jdeme.|Myslím, e je to v pohodì.
{10147}{10251}Tentokrát za to nemùu.|Doktor nastavil všechny svoje hodiny|o 25 minut dozadu.
{10257}{10286}Øekl jste Doktor?
{10290}{10386}Mám tomu rozumìt tak, e se stále|stıkáte s Dr. Emmettom Brownem, McFlyi?
{10410}{10457}Lístek za pozdní pøíchod pro vás, sleèno Parkerová.
{10474}{10547}A jeden pro vás, McFly.|Myslím, e je to u ètvrtı v øadì.
{10563}{10631}A teï vám dám jednu|radu zdarma, mladı mui.
{10636}{10709}Tento takzvanı Doktor Brown je nebezpeènı.|Je to skuteènı blázen.
{10714}{10775}Kdy se s ním budete nadále stıkat,|tak skonèíte s velkımi problémy.
{10780}{10816}Ano, pane.
{10822}{10895}Máte problémy s chováním,|protoe jste lajdák.
{10914}{11005}Pøipomínáte mi vašeho otce, kdy|sem chodil. On byl také lajdák.
{11015}{11063}Mùu u jít, pane Stricklande?
{11068}{11151}Vaše skupina vystoupí na|soutìi hned po vyuèovaní.
{11156}{11211}Ale proè si dìlat starosti?|Nemáte ádnou šanci.
{11217}{11261}Jste stalé podobnìjší svému otci.
{11265}{11356}ádnı McFly toti nikdy nic|neznamenal v historii mìsta Hill Valley.
{11404}{11457}Jasnì, ale historie se bude mìnit.
{11512}{11544}{y:i}Další, prosím.
{11768}{11804}{y:i}V poøádku.
{11820}{11890}{y:i}Jsme skupina Pinheads.
{11925}{11959}{y:i}Raz, dva, tøi.
{12431}{12501}{y:i}Dobøe, to staèí. Dìkujeme vám.
{12506}{12555}{y:i}Pøestaòte.
{12567}{12621}{y:i}Obávám se, e jste pøíliš hluèní.
{12641}{12677}{y:i}Další, prosím.
{12731}{12775}{y:i}Další skupina, prosím.
{12836}{12900}{y:i}Zvolte znovu starostu Goldie Wilsona.
{12904}{12953}{y:i}Jeho jméno je zárukou pokroku.
{12957}{13000}{y:i}"Pøíliš hluèní." Nemùu tomu uvìøit.
{13003}{13065}Nikdy nedostaneme šanci|zahrát si na veøejnosti.
{13072}{13128}Marty, jeden neúspìch|není konec svìta.
{13133}{13187}Já si jen nemyslím, e jsem|stvoøenı pro hudbu.
{13190}{13275}Ale ty jsi skuteènì dobrı|a kazeta s nahrávkami je vıborná.
{13279}{13333}Musíš ji poslat do|nahrávací spoleènosti.
{13337}{13378}- Je to pøesnì tak, jak Doktor stále øíká.|- Já vím.
{13383}{13456}Pokud do toho dáš všechno,|mùeš dosáhnout èehokoliv.
{13469}{13512}To je dobrá rada.
{13515}{13600}Dobøe. Ale, co kdy jim tu kazetu pošlu|a jim se nebude líbit?
{13607}{13650}Co kdy øeknou, e jsem na nic?
{13654}{13703}Co kdy mi øeknou, "Nemáte ádnou budoucnost"?
{13707}{13761}To u bych skuteènì tìce snášel.
{13790}{13836}U zaèínám mluvit jako mùj otec.
{13837}{13886}- On není tak špatnı.|- Zachraòte hodiny naší radnice.
{13890}{13953}Vdy ti pøece pùjèí auto na zítra.
{13985}{14028}Sleduj to auto s náhonem|na všechny ètyøi.
{14044}{14103}- To je paráda.|- Nacouvej sem.
{14110}{14187}Jednoho dne, Jennifer. Jednoho dne.
{14201}{14275}Nebylo by skvìlé zajet|si s tou károu k jezeru?
{14311}{14375}Dozadu naházet pár spacákù.
{14412}{14459}Leet si pod hvìzdami.
{14462}{14506}- Pøestaò.|- Co?
{14528}{14586}Ví tvoje máma o té|zítøejší noci?
{14587}{14683}Ne. Máma si myslí,|e jdu s kamarády stanovat.
{14687}{14758}Moje máma by se zbláznila|kdyby vìdìla, e jdu s tebou.
{14762}{14808}Dostal bych standardní kázání o tom...
{14812}{14872}...jak ona nikdy takové vìci nedìlala,|kdy byla v mém vìku.
{14876}{14937}Podívej, já mám dojem, e|se narodila jeptiškou.
{14944}{15007}Ona jen chce aby jsi se choval slušnì.
{15012}{15062}Tak to nedìlá moc dobøe.
{15065}{15094}Hrozné.
{15097}{15181}Zachraòte hodiny naší radnice.|Zachraòte hodiny naší radnice.
{15187}{15279}Starosta Wilson podporuje akci|na záchranu hodin naší radnice.
{15286}{15387}{y:i}Pøed tøiceti lety, do ní udeøil|{y:i}blesk a od té doby nefungují.
{15394}{15503}Naše spoleènost pro záchranu památek|si myslí, e hodiny by mìli bıt uchované...
{15511}{15560}{y:i}...jako èást naší historie|{y:i}a kulturního dìdictví.
{15562}{15606}- Tady máte ètvrák.|- Dìkuji.
{15610}{15653}Nezapomeòte si vzít letáèek.
{15658}{15701}{y:i}Zachraòte hodiny naší radnice!
{15747}{15772}Kde jsme to pøestali?
{15803}{15853}- Pøímo pøi tomhle.|- Jennifer!
{15925}{15979}To je mùj otec. Musím u jít.
{15985}{16012}Zavolám ti dnes veèer.
{16015}{16047}Budu u babièky.
{16050}{16106}Poèkej, napíšu ti èíslo.
{16228}{16251}Ahoj.
{17290}{17359}{y:i}Bravo, Tango, Delta 6-2-9.
{17364}{17427}{y:i}Odtáhnutí vozidla.|{y:i}Jednotko, prosím ozvìte se.
{17496}{17554}Perfektní. Fakt perfektní.
{17714}{17762}Nemùu uvìøit, e jsi mi pùjèil auto...
{17766}{17816}...a neøekl mi, e je v tak špatném stavu.
{17820}{17856}Mohl jsem se zabít.
{17861}{17918}Ale, Biffe. Nevšiml jsem si...
{17922}{18010}...e by to auto mìlo nìjakou|závadu, kdy jsem s ním jel.
{18016}{18049}Ahoj, synu.
{18052}{18093}Jsi slepı, McFlyi?
{18097}{18149}{y:i}Jak teda vysvìtlíš|{y:i}ten vrak venku?
{18155}{18229}Biffe, mùeme pøedpokládat...
{18236}{18305}...e ta škoda bude hrazena z tvé pojistky?
{18310}{18364}Z mé pojistky? Je to tvoje auto.
{18368}{18435}Z tvé pojistky se to zaplatí.|A kdo zaplatí za tohle?
{18440}{18533}Rozlil jsem na sebe pivo pøi nárazu.|Kdo zaplatí èistírnu?
{18540}{18584}{y:i}A kde je moje zpráva?
{18587}{18686}Ještì jsem to nestihl, myslel jsem si|e mám ještì dost èasu...
{18692}{18760}Haló? Haló? Je nìkdo doma?
{18779}{18835}Pøemıšlej, McFlyi. Pøemıšlej!
{18840}{18884}Já to musím dát ještì pøepsat.
{18888}{18985}Umíš si pøedstavit, co by se stalo, kdybych|odevzdal tu zprávu s tvım škrabopisem?
{18991}{19028}Vyhodili by mì.
{19032}{19093}Doufám, e to snad nechceš!
{19097}{19142}- Nebo snad ano?|- Samozøejmì, e ne.
{19146}{19203}Já si to nepøeji.
{19208}{19265}{y:i}Tak, podívej se.|{y:i}Dokonèím tu zprávu dnes veèer...
{19269}{19344}...a zítra ráno ti to|hned pøinesu.
{19350}{19396}Ale ne moc brzo.|V sobotu si rád pospím.
{19400}{19444}Máš rozvázané tkanièky.
{19453}{19509}Pokadé se necháš nachytat, McFlyi.
{19514}{19558}{y:i}Pìknì jsi si to tady zaøídil.
{19609}{19658}Dovezl jsem ti auto|a pøed dùm...
{19663}{19718}...a ty máš pro mnì jen tohle pivo?
{19891}{19941}Na co tak èumíš, ty hlavo dubová?
{19998}{20042}Pozdravuj ode mnì svou mámu.
{20114}{20162}Vím co mi chceš povìdìt, synu...
{20166}{20204}...a máš pravdu.
{20208}{20240}Máš pravdu.
{20255}{20279}Ale...
{20299}{20346}Biff mìl nade mnou vdy navrch...
{20350}{20461}...a já se obávám, e pøi|støetu bych neobstál.
{20489}{20530}Ale to auto, táto.
{20574}{20629}Vdy ho sešrotoval.|Úplnì.
{20661}{20709}Potøeboval jsem to auto na zítøejší veèer, táto.
{20713}{20788}Umíš si pøedstavit, jak to bylo pro mnì dùleité?
{20793}{20852}Já vím, a jediné co mùu øíct je...
{20870}{20904}Lituji.
{20913}{20962}Vìø mi, Marty, radši by jsi...
{20966}{21038}...si nemìl dìlat starosti|kvùli hudbì, potom máš z toho...
{21043}{21118}...hraní k tanci pouze bolení hlavy.
{21124}{21214}On má absolutní pravdu. Poslední,|co potøebuješ je bolení hlavy.
{21414}{21497}Dìti, tento koláè|musíme sníst sami.
{21515}{21569}Strıèka Joeyho znova nepustili|z vìzení.
{21628}{21703}Bylo by fajn, kdybyste mu alespoò napsali.
{21711}{21749}Strıèek "Kriminálník" Joey?
{21752}{21788}Je to tvùj bratr, mami.
{21792}{21878}Ano. Je to velmi potupné, mít strıèka,|kterı sedí v base.
{21888}{21936}Všichni dìláme v ivotì chyby, dìti.
{21940}{21980}K èertu. Nestíhám.
{21984}{22022}Davide, nemluv takhle!
{22026}{22085}Pojï sem a dej pusu své matce ne odejdeš.
{22089}{22160}Ale rychle mami, jinak|nestihnu autobus.
{22175}{22202}Uvidíme se pozdìji, táto.
{22233}{22276}Je na èase vymìnit olej.
{22354}{22376}Marty.
{22396}{22437}Já nejsem tvùj záznamník, ale...
{22441}{22496}kdy jsi byl venku|a truchlil nad tím autem...
{22501}{22546}...dvakrát ti volala|Jennifer Parkerová.
{22550}{22585}Nelíbí se mi.
{22589}{22664}Kadé dìvèe, které volá|chlapci si øíká o problémy.
{22670}{22736}Mami. Na tom není nic špatného,|kdy dìvèe zavolá chlapci.
{22741}{22829}Myslím, e je to hrozné, kdy|dìvèata takhle uhánìjí chlapce.
{22835}{22911}Ve vašem vìku jsem nikdy neuhánìla chlapce,|volala mu...
{22916}{22975}...nebo s ním sedìla sama|v zaparkovaném autì.
{22993}{23054}Jak se mám potom s nìkım seznámit?
{23079}{23131}Neboj se, to pøijde samo.
{23138}{23192}Tak jako jsem se seznámila já s tvım otcem.
{23197}{23269}To bylo pìknì hloupé.|Dìdeèek ho srazil autem.
{23279}{23312}Tak se to mìlo stát.
{23344}{23375}Kadopádnì...
{23386}{23465}...kdyby ho dìda nesrazil, tak|nikdo z vás by teï nebyl na svìtì.
{23470}{23506}No tak dobøe.
{23510}{23590}Jen nechápu, co táta dìlal|uprostøed cesty.
{23595}{23651}Jak to bylo, Georgi?|Díval jsi se na ptáky?
{23656}{23715}Coe, Lorraine? Co?
{23719}{23786}Prostì, dìdeèek ho srazil autem...
{23791}{23840}...a pøivedl ho k nám domù.
{23865}{23909}Vypadal tak bezmocnı.
{23977}{24046}Jako ztracené štìòátko.|A moje srdce mu od té doby patøilo.
{24051}{24124}Ano, my víme.|Tu historku jsme vyslechli snad milionkrát.
{24129}{24161}{y:i}Bylo ti ho líto.
{24165}{24236}Tak si se rozhodla, e s ním pùjdeš|na ten tanec 'Ryby pod moøskou hladinou'.
{24241}{24311}Ne. Jmenovalo se to|'Okouzlení pod moøskou hladinou'.
{24335}{24407}Naše první schùzka.|Nikdy na to nezapomenu.
{24421}{24505}Té noci byla hrozná bouøka.|Pamatuješ si to, Georgi?
{24573}{24656}Váš otec mì poprvé políbil na taneèním parketu.
{24713}{24762}A tehdy jsem si uvìdomila...
{24767}{24840}...e s ním strávím zbytek|svého ivota.
{24931}{24963}Ale ne.
{25532}{25558}Haló.
{25561}{25622}{y:i}Marty, doufám e jsi nezaspal!|Doktore.
{25656}{25718}Ne. Ne, nebláznìte.
{25725}{25791}{y:i}Poslouchej, tohle je velmi dùleité.|{y:i}Zapomnìl jsem si svou videokameru.
{25797}{25862}{y:i}Mùeš se po cestì sem|{y:i}u mnì stavit a vzít ji?
{25866}{25926}Jasnì. U jsem na cestì.
{26512}{26582}Einsteine! Kde je doktor, chlapèe?
{27888}{27913}Doktore!
{27944}{27997}- Marty! Zvládl jsi to!|- Jasnì.
{28006}{28107}Vítej u mého nejnovìjšího experimentu.|Na tohle jsem èekal celı svùj ivot.
{28113}{28150}Aha, tohle je DeLorean..
{28152}{28243}Na všechny otázky ti odpovím, ale|teï nastav kazetu a jdeme na to.
{28249}{28304}- To je nìjaká speciální kombinéza?|- Nechme to zatím bıt.
{28308}{28358}- Teï ne.|- Pøipravenı.
{28376}{28468}Dobrı veèer. Jsem Dr. Emmett Brown a|stojím na parkovišti u Two Pines.
{28474}{28556}Je sobota ráno,|26. øíjna 1985, je 1:18 ráno.
{28560}{28613}{y:i}Tohle je èasová zkouška èíslo jedna.
{28618}{28685}Jdeme na to, Einie. Nastup si.
{28693}{28738}Dovnitø. Sedni si.
{28747}{28794}Pøipoutáme tì.
{28932}{28963}V poøádku.
{28997}{29057}Prosím všimnìte si, e|Einsteinovy hodinky...
{29063}{29131}...jsou pøesnì synchronizované|s mımi hodinkami.
{29135}{29187}- Máš to?|- Jasnì. Je to tam, Doktore.
{29251}{29322}Šastnou cestu, Einsteine.|Pozor na hlavu.
{29457}{29519}Vy jste to pøepojil na øízení auta?
{29524}{29569}- Sleduj.|- Jasnì. Ok.
{29574}{29606}Mám to.
{29700}{29725}Jeiši!
{29844}{29882}Ne mnì! To auto!
{30301}{30357}Jestli jsou mé vıpoèty správné...
{30368}{30429}...a to zlatíèko dosáhne rychlosti|88 mil za hodinu...
{30441}{30497}...tak zaiješ neuvìøitelnou vìc.
{31354}{31394}Sleduj!
{31829}{31882}Co jsem ti øíkal?
{31888}{31966}88 mil za hodinu!
{32044}{32157}Hodiny ukazují pøesnì|1:20 a nula sekund!
{32204}{32247}Jeiši kriste!
{32251}{32307}Jeiši kriste, Doktore!|Vy jste Einsteina úplnì vymazal!
{32312}{32369}Uklidni se. Nikoho jsem nevymazal.
{32376}{32474}Molekulová struktura Einsteina i|auta je absolutnì neporušená.
{32491}{32524}Tak kde k èertu jsou?
{32526}{32599}Vhodnìjší otázka je,|{y:i}V jakém èase k èertu jsou?
{32604}{32706}Einstein se stal prvním tvorem na svìtì,|kterı cestoval v èase.
{32722}{32783}Poslal jsem ho do budoucnosti.
{32811}{32866}Abych byl pøesnı,|jednu minutu do budoucnosti,
{32870}{32944}Pøesnì v 1:21 a nula sekund...
{32949}{33018}...se potkáme s ním|i se strojem èasu.
{33103}{33149}Poèkejte, Doktore.
{33191}{33260}Snaíte se mi øíct, e jste|sestrojil stroj èasu...
{33289}{33340}- ...z DeLorean?|- Pøesnì tak, já to vidím takhle...
{33345}{33438}...kdy u jdeš zabudovat stroj èasu|do auta, tak proè to neudìlat stylovì?
{33444}{33520}Navíc, konstrukce z nehoølavé oceli umonila...
{33553}{33585}Pozor!
{34663}{34730}- Co je? Je to horké?|- Je to studené. Velmi studené.
{34822}{34873}Einsteine, ty malı èertíku!
{34929}{35017}{y:i}Einsteinovy hodinky ukazují pøesnì|{y:i}o minutu ménì a ještì stále tikají!
{35105}{35142}- Je v pohodì.|- Je v poøádku.
{35146}{35198}On vùbec netuší,|e se nìco stalo.
{35202}{35264}Ta cesta probìhla tak rychle,|e ani nic nezaregistroval.
{35269}{35329}Proto jsou jeho hodinky pozadu|pøesnì o jednu minutu.
{35333}{35420}Pøeskoèil tu minutu a ihned|dorazil v tento èasovı moment.
{35426}{35481}Ukáu ti jak to funguje.
{35520}{35590}Nejprve si zapneš èasové okruhy.
{35684}{35777}Tohle ti ukazuje kam jdeš,|tohle kde jsi a tohle kde jsi byl.
{35783}{35840}Vloíš cílovı èas pøes tuto klávesnici.
{35844}{35927}Øeknìme, e chceš vidìt podepsání|Deklarace Nezávislosti.
{35980}{36027}nebo bıt svìdkem narození Krista.
{36102}{36164}Ale tady je datum, které vejde|do historie vìdy.
{36169}{36232}5. listopad 1955.
{36324}{36359}Ano. Samozøejmì.
{36363}{36431}5. listopad 1955.
{36449}{36490}Co se tehdy stalo?
{36518}{36574}V ten den jsem dostal nápad|s cestováním v èase.
{36586}{36621}{y:i}Pamatuji si to úplnì jasnì.
{36624}{36671}Stál jsem v koupelnì a zavìšoval hodiny.
{36676}{36741}Dladièky byli mokré. Já jsem se|uklouzl a udeøil se hlavou o záchod.
{36745}{36789}A kdy jsem se probral,|mìl jsem zjevení.
{36793}{36878}Vizi. Obrázek v mé hlavì.|Obrázek tohoto.
{36894}{36955}{y:i}Tohle umoòuje cestovaní v èase.
{36971}{37012}Proudovı kondenzátor.
{37021}{37048}Proudovı kondenzátor?
{37052}{37158}Potøeboval jsem témìø 30 rokù|a celé bohatství své rodiny ne|jsem vizi z toho dne zrealizoval.
{37173}{37224}Mùj boe, to bylo skuteènì tak dlouho?
{37243}{37301}Všechno se to tu hroznì zmìnilo.
{37334}{37422}Pamatuji si, e všude kam jsi se podíval byla|polnohospodáøská pùda.
{37462}{37518}Starı Peabody to tu všechno vlastnil.
{37551}{37641}On mìl ten bláznivı nápad tu|vysadit borovice.
{37736}{37815}To je...|To je parádní objev, Doktore. Je to skvìlé.
{37830}{37889}Jezdí se s tím na|bezolovnatı benzín?
{37894}{37982}Bohuel, ne. Potøebuje to vìtší sílu, plutonium.
{37987}{38039}Plutonium. Poèkat.
{38044}{38107}Øíkáte, e tahle mašinka je nukleární?
{38115}{38147}Natáèej.
{38151}{38193}Ne, tahle mašinka je elektronická...
{38197}{38294}...ale potøebuji nukleární reakci|abych získal 1.21 gigawattu elektøiny.
{38299}{38375}Pøeci nemùete pøijít do obchodu|a koupit si plutonium.
{38389}{38435}{y:i}Vy jste to ukradl?
{38480}{38570}Samozøejmì. Skupinì Libíjskıch teroristù.|Chtìli abych jim udìlal bombu.
{38576}{38678}Sebral jsem to plutonium a jim jsem dal|nefunkèní bombu plnou odpadu.
{38684}{38751}Pojïme. Dáme ti oblek proti ozáøení.|- Jeiši!
{39465}{39522}Teï je to bezpeèné. Všechno je|a po èáru.
{39568}{39613}Teï ty kazety neztra.
{39617}{39662}Potøebuji je jako dokumentaci.
{39666}{39719}Tohle dáme zpìt. A pojïme na to.
{39780}{39820}Skoro jsem zapomnìl na mùj kuføík.
{39825}{39888}Co kdy budu v budoucnosti potøebovat|bavlnìné spodní prádlo.
{39893}{39962}- Jsem alergickı na všechno syntetické.|- Budoucnost.
{39971}{40013}- Tam teï jdete?|- Pøesnì tak.
{40017}{40118}25 rokù. Vdy jsem snil o tom vidìt|budoucnost na vlastní oèi...
{40124}{40173}...vidìt pokrok lidstva.
{40178}{40204}Proè ne?
{40208}{40287}Taky uvidím, kdo vyhraje|dalších 25 svìtovıch sérií.
{40308}{40331}Doktore.
{40366}{40421}Navštivte mì, kdy tam budete.
{40441}{40499}To rozhodnì udìlám. Natáèej.
{40654}{40719}Já, Dr. Emmett Brown...
{40751}{40812}...se vydávám na historickou cestu.
{40866}{40909}Na co to myslím?
{40913}{40963}Skoro jsem si zapomnìl vzít|plutonium navíc.
{40967}{41026}Jak bych se dostal zpìt?|Jedna dávka rovná se jedna cesta.
{41030}{41077}Musel jsem asi ztratit rozum.
{41140}{41178}Co je, Einie?
{41383}{41409}Mùj boe.
{41423}{41487}Našli mì. Nevím jak,|ale našli mì.
{41491}{41542}Utíkej, Marty!|- Kdo?
{41555}{41607}No kdo myslíš? Líbijèani!
{41693}{41728}Do prdele!
{41825}{41863}Upoutám jejich pozornost!
{42060}{42092}Doktore, poèkejte!
{42435}{42465}Ne!
{42487}{42529}Bastardi!
{42981}{43008}Za ním!
{43156}{43186}Za ním!
{44157}{44210}Pojïme! Pohni se! K èertu!
{44251}{44281}Jeiši!
{44766}{44799}Do prdele!
{44819}{44884}Podíváme se, jestli dokáete jet devadesátkou.
{46126}{46158}Tati, co je to?
{46162}{46196}Co je to, tati?
{46200}{46275}Vypadá to jako letadlo bez køídel.
{46292}{46364}To není letadlo. Podívej.
{46865}{46896}Nedívejte se!
{46900}{46938}Poslouchejte...
{47233}{47260}Haló.
{47337}{47367}Promiòte.
{47452}{47490}Omlouvám se za tu stodolu.
{47572}{47647}Ono to zmutovalo do lidské podoby.|Zastøel to!
{47697}{47751}Tu máš, ty zmutovanı zkurvysynu.
{47859}{47891}Poèkejte!
{47947}{47984}Zastøel to, tati!
{48043}{48113}- Moje borovice! Proè to...
{48165}{48244}Ty vesmírnı bastarde!|Znièil jsi mi borovici!
{48352}{48395}Dobøe, McFlyi.
{48399}{48450}Dej se dohromady. To je všechno jen sen.
{48454}{48519}Jen velmi intenzívní sen.
{49319}{49444}Bydlete v domì zítøka...u dnes!|Firma LYONE STATES.
{49554}{49627}- Poslouchejte, musíte mi pomoct.|- Nezastavuj, Wilbure!
{49694}{49725}To není moné.
{49873}{49910}To je šílené.
{50010}{50046}Naskoè.
{50066}{50101}Perfektní.
{52764}{52851}Vitejte v Hill Valley.|V krásném mìstì pro ivot.|Prosím jezdìte opatrnì.
{52866}{52944}{y:i}Pamatujte, obèané,|{y:i}budoucnost je ve vašich rukách.
{52950}{53034}{y:i}Jestli vìøíte v pokrok, tak znovu|{y:i}zvolte starostu Reda Thomase.
{53044}{53090}{y:i}Jeho jméno je zárukou pokroku.
{53096}{53153}{y:i}Pokrokovı program starosty|{y:i}Reda Thomase...
{53159}{53216}{y:i}...znamená více pracovních|{y:i}pøíleitostí, lepší vzdìlaní...
{53221}{53291}{y:i}...vìtší rozvoj mìsta a niší danì.
{53296}{53382}{y:i}V den voleb dejte svùj hlas|{y:i}nejlepšímu kandidátovi.
{53389}{53440}{y:i}Zvolte znovu starostu Reda Thomase.
{53524}{53569}Tohle musí bıt sen.
{53978}{54027}Hej, chlapèe.|Copak se s tebou potopila loï?
{54051}{54108}- Coe?|- No e proè máš záchrannou vestu.
{54237}{54274}Chci si jen zavolat.
{54291}{54327}Je tam vzadu.
{54391}{54423}Brown.
{54474}{54508}Skvìlé. Vy ijete.
{54803}{54834}Zdvihnìte to.
{55013}{55104}Víte, kde je Riverside 1640..|- Objednáš si nìco, chlapèe?
{55157}{55184}Jasnì.
{55192}{55230}{y:i}Dejte mi minerálku.
{55239}{55296}To ti nemùu dát, jestli si nedáš nìco jiného.
{55301}{55346}V poøádku.|Dejte mi teda Pepsi "Bez".
{55351}{55413}Jestli myslíš Pepsi bez placení,|tak to by nešlo.
{55419}{55490}Tak mi dejte jen nìco|bez cukru, dobøe?
{55498}{55540}Dobøe, nìco bez cukru.
{55729}{55757}Hej, McFlyi.
{55815}{55853}Co tady dìláš?
{55878}{55902}Biffe.
{55909}{55967}S tebou mluvím, McFlyi, ty blbej Ire!
{55971}{56062}- Biffe. Chlapci. Jak se máte?|- Udìlal jsi mi u ten domácí úkol?
{56083}{56145}No, myslel jsem, e|to má bıt a na pondìlí..
{56150}{56215}Haló? Haló? Je nìkdo doma?
{56229}{56274}Pøemıšlej, McFlyi. Pøemıšlej!
{56278}{56321}Musím mít dost èasu, abych to ještì pøepsal.
{56325}{56411}Umíš si vùbec pøedstavit, co by se stalo,|kdybych to odevzdal napsané tvım škrabopisem?
{56416}{56458}Vyhodili by mì ze školy.
{56461}{56520}Snad si nìco takového nepøeješ.
{56574}{56614}- Nebo snad ano?|- Samozøejmì, e ne.
{56616}{56662}- Ne.|- To si nepøeji.
{56665}{56757}- Na co tak èumíš, hlavo dubová?|- Podívej na tu záchrannou vestu.
{56763}{56803}Blbeèek se bojí, e se utopí.
{56807}{56850}Tak co mùj domácí úkol, McFlyi?
{56878}{56916}Dobøe, Biffe.
{56921}{57028}Dokonèím to dnes veèer a zítra|ráno ti to donesu.
{57040}{57121}Ale ne moc brzo, v sobotu si rád pospím.|Máš rozvázané tkanièky!
{57139}{57186}Vdy se necháš nachytat, McFlyi.
{57190}{57276}- U tì tu podruhé nechci vidìt.|- Dobøe. V poøádku. Ahoj.
{57807}{57865}- Co je?|- Ty jsi George McFly!
{57877}{57921}Ano. A kdo jsi ty?
{57925}{57986}Proè necháváš ty blbce s tebou tak zametat?
{57990}{58021}Jsou vìtší ne já.
{58026}{58078}Musíš se jim vzepøít.|A mít úctu k sobì samému.
{58084}{58189}Jestli budou lidi po tobì šlapat u teï,|tak budou po tobì šlapat celı ivot.
{58196}{58267}Podívej se na mnì. Myslíš, e|chci bıt navdy v téhle krèmì?
{58273}{58315}Pozor na ústa, Goldie.|- Ne, pane!
{58319}{58376}Já nìco udìlám,|pùjdu do veèerní školy.
{58379}{58430}Jednoho dne, budu nìkdo.
{58434}{58478}Je to tak. On bude starostou.
{58482}{58514}Jasnì, já budu...
{58530}{58563}starostou!
{58583}{58673}To je ale dobrı nápad!|Stanu se starostou.
{58678}{58765}- Barevnı starosta. U to vidím.|- Poèkejte a uvidíte. Budu starostou.
{58771}{58826}A budu nejmocnìjším muem|v Hill Valley...
{58829}{58873}...a budete sledovat jak já tohle mìsto vyèistím.
{58877}{58937}Dobøe. Mùeš zaèít s naší podlahou.
{59008}{59057}Starosta Goldie Wilson.
{59061}{59104}To se mi moc líbí.
{59407}{59486}Hej, tati! Georgi! Hej, ty na tom kole!
{60240}{60287}On tu šmíruje!
{60424}{60453}Táta!
{60758}{60808}Poèkej chvíli. Kdo jsi?
{60853}{60953}Stello! Jedno z tìch proklatıch dìcek|mi právì vbìhlo pod kola!
{60979}{61041}{y:i}Hned pojï sem!|{y:i}Pomùeš mi s ním dovnitø!
{61177}{61211}Mami?
{61216}{61252}{y:i}Jsi to ty?
{61262}{61296}Jsem tady.
{61303}{61336}{y:i}Jen odpoèívej.
{61398}{61459}{y:i}Spal jsi skoro 9 hodin.
{61515}{61571}Mìl jsem hroznı sen.
{61598}{61670}Zdálo se mi, e jsem se|vrátil do minulosti.
{61684}{61714}{y:i}Bylo to hrozné.
{61734}{61764}Nu...
{61776}{61854}...jsi v bezpeèí a jsi zpìt|v starém dobrém roce 1955.
{61888}{61921}1955?
{62037}{62098}Ty jsi moje m...
{62105}{62149}- Jmenuji se Lorraine.
{62157}{62224}Lorraine Bainesová?|- Ano.
{62252}{62288}Ale ty jsi...
{62291}{62326}Ty jsi tak...
{62328}{62405}Ty jsi taková štíhlá!
{62412}{62484}Odpoèiò si, Calvine.|Dostal jsi velkou ránu do hlavy.
{62592}{62632}Kde mám kalhoty?
{62640}{62674}Tam jsou...
{62689}{62726}...na mojí skøíni.
{62762}{62827}Ještì nikdy jsem nevidìla|fialové prádlo, Calvine.
{62838}{62907}Calvine?|Proè mi stále øíkáš Calvine?
{62912}{62976}To je tvoje jméno, ne? Calvin Klein.
{62990}{63045}Máš to napsané všude na prádle.
{63069}{63124}Asi ti øíkají Cal.
{63134}{63177}Ne, obvykle mi lidi...
{63195}{63230}...øíkají Marty.
{63274}{63319}Ráda tì poznávám, Calvine..
{63353}{63386}Marty...
{63421}{63449}...Kleine.
{63613}{63688}- Nevadí ti, e jsem si pøisedla?|- Ne. V poøádku.
{63695}{63753}Ne. To je dobrı. V poøádku.|Bez problémù.
{63800}{63859}Máš na hlavì velkou bouli.
{63894}{63948}- Lorraine, jsi tam nahoøe?
{63952}{63996}Mùj boe! To je moje matka!
{64001}{64070}Rychle! Obleè si kalhoty!
{64271}{64324}Marty, jak dlouho jste u v pøístavu?
{64328}{64386}- Prosím?|- Pøedpokládám, e jste námoøník.
{64390}{64446}Protoe máte na sobì tu|záchrannou vestu.
{64452}{64484}Jsem u pobøení hlídky.
{64487}{64588}Same, tady je ten mladı mu, kterého|jsi srazil. Je v poøádku, díky bohu.
{64595}{64646}Co jste dìlal uprostøed silnice?
{64651}{64713}Nevšímejte si ho.|Ten má zase náladu.
{64719}{64784}Pøestaò si hrát s tou bednou|a pojï sem na veèeøi.
{64788}{64832}S naší Lorraine se u znáte.
{64836}{64883}Tohle je Milton, tohle je Sally...
{64888}{64984}...to je Toby, a v té dìtské záhradce je náš malı Joey.
{65036}{65082}Take, ty jsi mùj strıèek Joey.
{65104}{65161}Pìknì si na ty møíe zvykej.
{65165}{65262}Ano. Malı Joey je velmi rád|v té dìtské ohrádce.
{65269}{65352}Vdy plaèe, kdy ho chceme vyndat,|tak ho tam necháváme skoro poøád.
{65358}{65414}Tak, Marty. Doufám, e máte rád sekanou.
{65423}{65490}- No, poslyšte. Mìl bych radši..|- Tady si sedni, Marty.
{65511}{65613}Same, pøestaò si hrát s tou bednou|a pojï se s námi naveèeøet.
{65660}{65700}Podívejte na tu parádu.
{65704}{65774}Teï se mùeme podívat na|Jackieho Gleasona i bìhem jídla.
{65970}{66051}Náš první televizor.|Otec ho dnes koupil.
{66073}{66112}Máte televizor?
{66125}{66191}No, jasnì.|Máme dva.
{66197}{66260}Paráda! To musíte bıt bohatí.
{66265}{66369}Zlato, on si z tebe jen utahuje.|Nikdo nemá dva televizory.
{66508}{66575}Hej to u jsem vidìl. To je klasika.
{66580}{66649}Ralph je tam obleèenı jako|mu z vesmíru.
{66658}{66732}Jak to myslíš, e jsi to u vidìl?|To je úplnì nové.
{66743}{66803}Jasnì, no, vidìl jsem to|v reprízách pro pamìtníky.
{66817}{66854}Co jsou to reprízy?
{66863}{66897}To brzy zjistíš.
{66900}{66954}Poslouchejte, Marty,|zdáte se mi nìjakı povìdomı.
{66959}{67004}Znám vaši matku?
{67035}{67080}Ano, myslím, e byste|ji mohli znát.
{67086}{67162}Potom bych ji asi mìla zavolat.|Nechci, aby si o vás dìlala starosti.
{67167}{67195}To nejde.
{67200}{67299}Vlastnì, nikdo není doma.
{67362}{67395}Zatím.
{67448}{67475}Poslouchejte.
{67478}{67538}Nevíte, kde je ulice Riverside Drive?
{67543}{67634}Je to na druhé stranì mìsta.|Jeden blok za Maple. Vıchodní èást.
{67644}{67720}Jeden blok za Maple.|To je pøeci ulice Johna F. Kennedyho.
{67760}{67806}Kdo je k èertu ten John F. Kennedy?
{67810}{67843}Mami?
{67855}{67915}{y:i}Kdy jsou Martyho rodièe|{y:i}mimo mìsto...
{67932}{67987}...nemyslíš, e by mohl|pøespat u nás?
{67991}{68047}Po tom všem jak|ho otec skoro zabil autem.
{68052}{68098}To je pravda, Marty.
{68104}{68189}Myslím, e byste u nás mìl zùstat.|Myslím, e za vás neseme zodpovìdnost.
{68194}{68274}- No, opravdu nevím.|- A mohl by spát v mém pokoji.
{68284}{68322}U musím jít!
{68331}{68381}Moc dìkuji.|Všichni jste byli skvìlí.
{68385}{68419}Uvidíme se pozdìji.
{68449}{68483}O mnoho pozdìji.
{68579}{68640}Je to velmi zvláštní mladı mu.
{68647}{68678}Je to idiot.
{68683}{68761}{y:i}Nemá ádné vychování.|{y:i}Jeho rodièe jsou asi také idioti.
{68782}{68866}{y:i}Lorraine, jestli budeš mít nìkdy dìti,|{y:i}jako je tohle, tak tì vydìdím.
{69781}{69814}Doktore?
{69829}{69865}Nic neøíkej.
{69896}{69955}ádná jména. Nechci o tobì nic vìdìt.
{69960}{69996}Poslouchejte, Doktore...|- Ticho!
{70000}{70038}Nic mi neøíkej.
{70041}{70090}Musíte mi pomoc...|- Ticho.
{70156}{70201}Budu ti èíst myšlenky.
{70206}{70288}Tak se na to podívejme.|Pøišel jsi sem zdaleka?
{70294}{70351}- Ano. Pøesnì.|- Nic neøíkej!
{70366}{70431}A chceš, abych si pøedplatil|"Saturday Evening Post".
{70435}{70495}- Ne.|- U ani slovo!
{70500}{70526}Ticho.
{70579}{70610}Peníze.
{70614}{70661}Chceš abych poslal nìjaké peníze...
{70665}{70720}...pro mladé èleny pobøení hlídky.
{70736}{70768}Doktore...
{70806}{70855}...pøišel jsem z budoucnosti.
{70859}{70928}Pøišel jsem se strojem èasu,|kterı jste vy sám sestrojil.
{70943}{71052}Teï mi musíte pomoc|dostat se zpìt do roku 1985.
{71091}{71122}Mùj boe!
{71235}{71285}Víš ty vùbec, co to znamená?
{71328}{71427}To znamená, e tato|proklatá vìc vùbec nefunguje!
{71433}{71533}Musíte mi pomoct. Vy jste jedinı, kdo|ví jak stroj èasu funguje.
{71540}{71574}Stroj èasu?
{71588}{71639}Nikdy jsem ádnı stroj èasu nevymyslel.
{71677}{71723}Dobøe. Já vám to dokáu.
{71737}{71811}Podívejte se na mùj øidièák.|Platí do roku 1987.
{71816}{71898}Podívejte se na moje datum narození.|Já jsem se vlastnì ještì ani nenarodil.
{71904}{71951}A podívejte se na tu fotku.
{71958}{72008}Mùj bratr, moje sestra a já.
{72012}{72087}Podívejte se na ten svetøík, Doktore.|Tøída roku 1984.
{72113}{72206}To je bìná fotomontá.|Tvému bratrovi odstøihli vlasy.
{72231}{72285}Øíkám vám pravdu.|Musíte mi vìøit.
{72290}{72356}Tak mi tedy øekni chlapèe z budoucnosti...
{72368}{72462}...kdo je prezidentem Spojenıch Státù v roce 1985?
{72468}{72549}- Ronald Reagan.|- Ronald Reagan? Ten herec?
{72590}{72648}A kdo je potom více-prezidentem?|Jerry Lewis?
{72679}{72760}A Jane Wymanová je první dámou, e?|- Poèkejte, Doktore!
{72765}{72816}A Jack Benny má na starosti|státní pokladnu.
{72820}{72850}- Poslouchejte mì.
{72855}{72934}Dnes bylo tìch srandièek u dost.|Dobrou noc, chlapèe z budoucnosti!
{72939}{72969}- Ne, poèkejte, Doktore.
{72973}{73073}Ta boule na vaší hlavì.|Vím jak se vám to stalo. Øíkal jste mi to.
{73079}{73138}Stál jste v koupelnì a|zavìšoval hodiny...
{73143}{73194}...a potom jste se smekl|a udeøil se hlavou o záchod.
{73198}{73284}A tehdy jste dostal ten nápad s tím|proudovım kondenzátorem, kterı...
{73290}{73364}...umoòuje cestovaní v èase..
{73680}{73776}Rozbil se mi startér,|tak jsem to tady schoval.
{74032}{74077}Kdy jsem se probral|ve své koupelnì...
{74104}{74136}{y:i}...nakreslil jsem tohle.
{74232}{74266}Proudovı kondenzátor.
{74704}{74737}Ono to funguje!
{74796}{74831}Funguje to!
{74863}{74918}Tak jsem nakonec vymyslel|nìco, co funguje!
{74947}{74991}To se mùete vsadit, e to funguje.
{75023}{75084}Musíme to nìjak odtáhnout do|mé laboratoøe.
{75095}{75138}Musíme tì dostat domù!
{75156}{75190}To je ono.
{75243}{75290}{y:i}Nechme to teï tak.
{75294}{75350}Jo, vdy to jsem já!|Podívej se na mnì!
{75357}{75406}- Jsem starı mu!|{y:i}- Jsem Dr. Emmett Brown.
{75410}{75457}{y:i}Stojím na parkovišti u|{y:i}Two Pines.
{75461}{75508}Díky bohu, mám stále nìjaké vlasy.
{75512}{75558}Co to mám na sobì obleèené?
{75562}{75612}To je oblek proti ozáøení.
{75616}{75656}Oblek proti ozáøení?
{75660}{75737}Samozøejmì. Kvùli strachu|z atomovıch válek.
{75764}{75833}To je skuteènì neuvìøitelné.
{75841}{75900}Pøenosné televizní studio.
{75909}{75997}Není divu, e váš prezident musí bıt|hercem. Musí vypadat dobøe v televizi.
{76003}{76047}- Teï pøijde ta èást.
{76078}{76178}{y:i}Tahle mašinka je elektronická, ale potøebuji|{y:i}nukleární reakci, abych získal 1.21 gigawattu.
{76185}{76230}Co jsem to øíkal?
{76313}{76384}{y:i}...tahle mašinka je elektronická,|{y:i}ale potøebuji nukleární reakci...
{76390}{76480}{y:i}-...abych získal 1.21 gigawattu...|-1.21 gigawattu!
{76517}{76566}1.21 gigawattu.
{76620}{76656}Sakra!
{76710}{76769}Co je k èertu ten gigawatt?
{76787}{76836}Jak jsem mohl bıt takovı lehkomyslnı?
{76841}{76884}1.21 gigawattu!
{76888}{76949}Thomas Alva Edison, kde jsem mohl|získat takovou energii, co?
{76953}{76989}To se nedá, nebo snad ano?
{76993}{77072}Doktore, podívejte. Potøebujeme|jen trochu plutonia.
{77090}{77183}Jsem si jistı, e v roce 1985 bude|plutonium v kadé drogérii...
{77189}{77252}...ale v roce 1955, to je|nesplnitelné pøání.
{77257}{77326}Marty, je mi líto, ale|asi tu u nás ztvrdneš.
{77368}{77416}Doktore, ztvrdnout tady?|Nemùu tady ztvrdnout.
{77420}{77472}Já iju v roce 1985.
{77477}{77525}- Mám tam dìvèe.|- Je pìkná?
{77541}{77578}Doktore, ona je fantastická.
{77601}{77651}A je do mnì udìlaná. Podívejte se.
{77660}{77704}{y:i}Podívejte, co mi sem napsala.
{77712}{77752}{y:i}To mluví za všechno.
{77773}{77834}Doktore, jste moje jediná nadìje.
{77850}{77927}Marty, je mi líto, ale jedinı zdroj energie,|kterı dokáe vyprodukovat...
{77932}{78006}...1.21 gigawattu elektøiny|je blesk.
{78044}{78097}Co jste to øíkal?|- Blesk.
{78101}{78188}Bohuel, nikdy nevíme,|kdy nebo kam blesk udeøí.
{78240}{78266}My to víme.
{78394}{78421}To je ono!
{78440}{78491}Tady máme odpovìï.
{78499}{78554}Tady je napsané, e blesk...
{78558}{78657}...zasáhne radnièní hodiny pøesnì|ve 22:04 a to pøíští sobotu.
{78748}{78827}Kdybychom nìjak dokázali|svézt tu sílu blesku...
{78859}{78936}...do proudového kondenzátoru...
{78970}{79004}{y:i}...tak by to mohlo fungovat.
{79020}{79115}Pøíští sobotu tì pošlu|zpìt do budoucnosti!
{79142}{79185}V poøádku. Sobota je super.
{79189}{79277}Mùu strávit tıden v roce 1955.|Porozhlédnu se tu. Vy mi ukáete okolí.
{79289}{79354}To je absolutnì vylouèené.|Ty nesmíš opustit tenhle dùm.
{79359}{79405}Nesmíš nikoho vidìt ani|s nikım mluvit.
{79409}{79508}Všechno, co udìláš, mùe mít vliv|na budoucí události. Rozumíš?
{79536}{79580}Ano. Jasnì. Dobøe.
{79598}{79631}Marty...
{79638}{79710}...setkal jsi se dnes ještì s nìkım dalším kromì mnì?
{79762}{79835}Ano, moná jsem tak nìjak|narazil na své rodièe.
{79840}{79921}Sakra! Uka mi ještì jednou|tu fotku tvého bratra.
{80015}{80098}Pøesnì jak jsem si myslel. Toto dokazuje|moji teorii. Podívej se na svého bratra.
{80127}{80201}Zmizela mu hlava.|Jako by byla vymazaná.
{80244}{80291}Vymazaná z existence.
{80429}{80491}Fakt to tady vyèistili.|Vypadá jako nová.
{80496}{80576}Podle mé teorie jsi zabránil|prvnímu setkání tvıch rodièù.
{80581}{80656}Jestli se nesejdou, nezamilují se,|nevezmou se a ani nebudou mít dìti.
{80663}{80716}Proto tvùj bratr postupnì mizí.
{80720}{80801}Potom následuje tvoje sestra.|A pokud nenapravíme škody, tak potom i ty.
{80807}{80875}To je síla.|- To se silou nemá nic spoleèného.
{80880}{80915}Kterı z nich je tvùj otec?
{80953}{80979}To je on.
{80995}{81046}Fajn, kluci, fajn.
{81093}{81167}Velmi vtipné.|Chováte se doopravdy velmi dospìle.
{81174}{81216}Moná jsi byl adoptovanı.
{81219}{81277}Fajn, velmi dospìlé, velmi.
{81302}{81361}Ok, zdvihnìte mi knihy.|- McFlyi.
{81365}{81398}To je Strickland.
{81418}{81465}Jeiši, copak ten chlap nikdy|nemìl vlasy?
{81469}{81528}Dej se dohromady. Jsi lajdák.
{81537}{81607}Chceš se po zbytek svého ivota|nechat utlaèovat?
{81613}{81634}Ne.
{81646}{81711}- Co na nìm tvoje matka vidìla?|- Já nevím.
{81718}{81805}Myslím, e jí ho bylo líto,|protoe ho její otec srazil autem.
{81824}{81875}On ale srazil mnì.
{81881}{81926}To je Florence Nightingalùv efekt.
{81931}{82012}Stává se to v nemocnicích, kdy|se sestøièky zamilují do pacientù.
{82017}{82046}Bì na to, chlapèe.
{82083}{82133}Georgi, kamaráde.
{82146}{82200}Všude jsem tì hledal.
{82204}{82282}Pamatuješ si na mnì?|Vèera jsem ti zachránil ivot.
{82305}{82376}- Jasnì.|- Chtìl bych tì s nìkım seznámit.
{82486}{82512}Lorraine?
{82533}{82561}Calvine!
{82587}{82651}Chci tì seznámit s mım dobrım pøítelem.|George McFly.
{82655}{82730}Ahoj. Je mi skuteènì potìšením|se s tebou poznat.
{82762}{82821}- Jak tvoje hlava?|- Dobøe. Fajn.
{82832}{82911}Dìlala jsem si o tebe starosti od toho|veèera, co jsi utekl.
{82916}{82947}Jsi v poøádku?
{82982}{83039}- Promiò. Musím u jít.|- Pojï!
{83063}{83104}Není to krasavec?
{83206}{83282}- Ani se na nìho nepodívala.|- Je to vánìjší ne jsem si myslel.
{83287}{83359}Tvoje matka je zbláznìná do tebe|místo do tvého otce.
{83388}{83414}Poèkejte, Doktore.
{83418}{83502}Chcete mi øíct, e|moje matka po mnì jede?
{83507}{83567}- Pøesnì.|- To je síla.
{83575}{83623}Zase to slovo. "Síla".
{83627}{83724}Proè jsou vìci v budoucnosti "síla"?|Je nìjakı problém se zemskou gravitací?
{83730}{83806}Jedinı zpùsob jak je seznámit,|je kdy budou sami.
{83812}{83868}Musíme je dát dohromady...
{83877}{83924}...na nìjakém spoleèenském...
{83959}{84012}- Myslíte rande?|- Pøesnì!
{84028}{84091}Jakı druh rande?|Co dìlají dìti v 50-tıch letech?
{84108}{84158}Jsou to tvı rodièe.|Ty je musíš znát.
{84162}{84248}Jaké mají spoleèné zájmy?|Co rádi spolu dìlají?
{84261}{84286}Nic.
{84289}{84360}Podívej! Zanedlouho bude|rytmickı ceremoniální rituál.
{84369}{84447}"Okouzlení pod moøskou hladinou"!|Oni tam musí jít.
{84452}{84522}-Tam se poprvé políbí.|- Dobøe, chlapèe.
{84527}{84613}Dr se svého otce jako klíštì a postarej|se o to, e ji pozve na ten tanec.
{84626}{84669}Georgi, kamaráde...
{84681}{84755}... pamatuješ si to dìvèe, co jsem|ti pøedstavil, Lorraine?
{84904}{84943}Co to píšeš?
{84973}{85001}Pøíbìhy.
{85014}{85099}Science fiction pøíbìhy|o návštìvnících...
{85110}{85184}...pøicházejících na Zem|z jinıch planet.
{85236}{85320}Klobouk dolù!|Nevìdìl jsem, e dokáeš bıt kreativní.
{85336}{85400}- Dej mi nìjaké pøeèíst.|-Ne, ne.
{85405}{85472}Nikdy nikomu nedovolím|èíst mé pøíbìhy.
{85492}{85523}- Proè ne?
{85552}{85637}Co kdy by se jim nelíbili?|Co kdy by povìdìli, e jsem k nièemu?
{85687}{85769}To je asi dost nepochopitelné, e?
{85789}{85848}Ne, to vùbec ne.
{85880}{85939}Nechme to tak, Georgi.|Zpìt k Lorraine.
{85969}{86005}Doopravdy se jí líbíš.
{86036}{86099}Øekla mi, e ti mám vzkázat,|e chce, aby jsi ji pozval ...
{86104}{86149}... na tanec "Okouzlení pod moøskou hladinou".
{86153}{86176}- Vánì?|- Jasnì.
{86183}{86248}Jediné, co musíš udìlat, je zajít za ní|a zeptat se jí.
{86279}{86330}Hned teï?|Tady v jídelnì?
{86334}{86418}Co kdy poví ne? Nevím, jestli bych snesl takovı druh odmítnutí.
{86463}{86554}A kromì toho, myslím, e by radši|šla s nìkım jinım.
{86589}{86615}- S kım?
{86663}{86685}S Biffem.
{86723}{86780}- Nezdráhej se tak. Pojï.|- Bì pryè.
{86785}{86830}Víš, e to chceš.
{86835}{86881}Víš, e to ode mnì chceš.
{86885}{86952}Zavøi si ty sprostá ústa.|Já nejsem taková.
{86977}{87038}Moná, e jsi, jen o tom ještì nevíš.
{87047}{87087}Dej ty špinavé ruce pryè.
{87091}{87158}Slyšel jsi ji.|Øíkala, abys dal ty ruce ...
{87178}{87201}... pryè.
{87234}{87261}Prosím.
{87283}{87325}Co je tobì do toho, blbèe?
{87360}{87408}Øíkal sis o to.
{87652}{87724}Kdy si tady novı,|tak toho necháme ...
{87738}{87763}... pro dnešek.
{87793}{87850}Tak proè nejsi poslušnı chlapeèek...
{87857}{87894}...a nevypadneš?
{88187}{88201}- Georgi!
{88251}{88296}Proè mì stále sleduješ?
{88300}{88411}Georgi, povídám ti, jestli|nepozveš Lorraine na ten tanec ...
{88417}{88485}-... budu toho litovat po zbytek svého ivota.|-Nemùu.
{88491}{88564}Propásl bych svùj oblíbenı televizní program,|Science Fiction Theatre.
{88569}{88647}Ano, ale Lorraine chce jít s tebou.
{88654}{88690}Dej jí šanci.
{88700}{88781}Nejsem ještì pøipravenı pozvat|Lorraine na ten tanec ...
{88800}{88870}... a ty ani nikdo jinı|na téhle planetì ...
{88879}{88929}... moje rozhodnutí nezmìní.
{89104}{89147}Science Fiction Theatre
{89911}{89938}Kdo jsi?
{90068}{90116}Ticho, pozemšane.
{90152}{90208}Moje jméno je Darth Vader.
{90332}{90412}Jsem mimozemšan|z planety Vulkán.
{90466}{90489}Marty!
{90569}{90619}-Marty! Marty!|-Georgi, kamaráde.
{90624}{90680}Nebyl jsi ve škole.|Co jsi dìlal?
{90684}{90751}Zaspal sem.|Potøebuji tvou pomoc.
{90756}{90825}Musím pozvat Lorraine,|ale nevím jak to udìlat.
{90830}{90886}Nic se neboj. Právì je v kavárnì.
{90891}{90938}Boe! Jak se to...?
{91008}{91047}Co tì donutilo zmìnit názor?
{91051}{91118}V noci za mnou pøišel|Darth Vader z planety Vulkán...
{91123}{91213}... a povìdìl mi, e jestli nepozvu|Lorrraine, roztaví mi mozek.
{91219}{91290}O tom roztavovaní mozku|si necháme jen pro sebe, dobøe?
{91295}{91370}- Jasòaèka.|- Dobøe. Tam je.
{91381}{91422}Prostì bì dovnitø a pozvi ji.
{91426}{91489}- Ale nevím, co øíct.|- Øekni cokoli.
{91493}{91574}Buï pøirozenı, øekni jí|první vìc, co tì napadne.
{91605}{91649}Mnì ale nic nenapadá.
{91653}{91703}Jeiši.|Zázrak, e sem se vùbec narodil.
{91707}{91766}- Co? Co?|- Nic.
{91804}{91866}Øekni jí, e jste si byli souzeni.
{91871}{91960}Øekni jí, e je nejkrásnìjším|dìvèetem, jaké jsi na svìtì vidìl.
{91966}{92004}Dìvèatùm se takové vìci líbí.
{92021}{92095}- Co to dìláš?|- Zapisuju si to. To je dobré.
{92100}{92171}- Ano. Ok. Mùeš si to napravit?|- Jasnì.
{92609}{92672}Lou, dej mi mléko.
{92712}{92737}S èokoládou.
{93132}{93161}- Lorraine.
{93177}{93207}My jsme si ...
{93225}{93269}...dušení.
{93288}{93316}Prosím?
{93367}{93428}Chtìl jsem øíct...
{93434}{93497}Poèkej chvíli.|Neznám tì odnìkud?
{93517}{93542}- Ano.
{93551}{93641}Ano. Jsem George. George McFly.
{93660}{93698}Jsme si dušení.
{93724}{93753}Chci øíct...
{93789}{93818}...souzeni.
{93903}{93924}- McFlyi.
{94035}{94095}Myslím, e jsem ti øíkal,|e se tady nemáš ukazovat.
{94166}{94207}Tak to tì bude nìco stát.
{94227}{94273}Kolik máš u sebe penì?
{94289}{94331}- Kolik chceš, Biffe?
{94538}{94570}V poøádku, ty frajere.
{94577}{94633}- Teï tì..|-Biffe. Co to je?
{94804}{94874}To je Calvin Klein. Mùj Boe,|je fantastickı.
{94899}{94962}Chlapèe! Clapèe, stùj! Zastav!
{95033}{95071}Vrátím ti ho.
{95084}{95124}Rozbil si ho!
{95133}{95176}Vra se!
{95218}{95259}Podívej se na nìho!
{95299}{95322}Chyte ho!
{95650}{95700}- Do auta! Rychle!
{95852}{95917}Na èem to jede?|- Deska s koleèkama.
{95922}{95958}Je úplnì senzaèní.
{95961}{96026}- Pojïme, pojïme!|- Pozor na to auto!
{96828}{96862}Zarazím ho tam.
{97051}{97074}Do prdele!
{97682}{97715}Díky, malièkı.
{97751}{97801}Já toho zkurvysyna dostanu.
{97811}{97882}- Odkud pochází?|- A kde bydlí?
{97902}{97934}Nevím...
{97948}{97994}...ale zjistím si to.
{98127}{98151}Mùj Boe.
{98169}{98237}Našli mì.|Nevím jak, ale našli mì.
{98245}{98281}Utíkej, Marty!
{98398}{98421}Mùj Boe.
{98450}{98515}Našli mì.|Nevím jak, ale našli mì.
{98522}{98553}Utíkej, Marty!
{98586}{98607}Doktore?
{98630}{98698}Ahoj, Marty.|Neslyšel jsem tì vejít.
{98724}{98782}Fascinující zaøízení,|tahle video bednièka.
{98809}{98847}Poslouchejte, Doktore.
{98851}{98962}Nepovìdìl jsem vám...|- Nikdo by nemìl znát svùj osud.
{98968}{99004}-Nerozumíte tomu.|-Ale ano.
{99008}{99066}Pokud budu vìdìt pøíliš mnoho,|ohrozím tím svou existenci...
{99071}{99127}...pøesnì tak jak jsi ohrozil ty svou.
{99178}{99222}Máte pravdu.
{99226}{99292}Ukáu ti svùj plán|jak tì poslat domù.
{99297}{99341}Prosím omluv hrubost|tohoto modelu.
{99345}{99403}Nemìl jsem èas pøesnì zohlednit|pomìry a namalovat to.
{99408}{99457}- To staèí.|- Dìkuji.
{99503}{99601}Od hodin z vrcholu radnièní vìe|spustíme elektrickı kabel ...
{99608}{99689}...dolù a natáhneme ho|mezi tyto dvì lampy.
{99702}{99793}Mezièasem jsem osadil stroj èasu|touto velkou tyèí a hákem ...
{99799}{99870}...ty smìøují pøesnì do|proudového kondenzátoru.
{99896}{99938}Ve spoèítané chvíli...
{99954}{100004}...odstartuješ dolù po ulici...
{100008}{100101}...budeš øídit pøímo ke kabelu,|zrychlíš na 88 mil za hodinu.
{100111}{100194}Podle letáèku, v sobotu veèer|pøesnì ve 22:04 ...
{100200}{100283}...udeøí do vìe blesk,|zelektrizuje kabel...
{100288}{100340}...a kdy se kontaktní|hák dotkne kabelu...
{100345}{100428}...vyšle se 1.21 gigawatu|do proudového kondenzátoru...
{100441}{100488}...a ten tì pošle zpìt do|roku 1985.
{100495}{100578}Dobøe, take teï. Sleduj.|Natáhni autíèko a pus ho.
{100636}{100681}Já budu simulovat blesk.
{100888}{100910}Pøipravit se.
{101150}{101176}Pozor.
{101298}{101322}Start.
{101766}{101821}- Naplòujete mì velkou|dávkou dùvìry.
{101825}{101909}Neboj se. Postarám se o nápady.|Ty se postarej o otce.
{101942}{101966}Mimochodem...
{101969}{102019}...jak to dnes šlo?|Pozval ji?
{102023}{102070}- Myslím, e jo.|- Co øíkala?
{102280}{102378}Tvoje matka! Musela tì sledovat!|Rychle! Zakryjeme stroj èasu.
{102702}{102756}Ahoj, Cal... Marty.
{102788}{102813}- Lorraine.
{102843}{102888}Jak jsi vìdìla, e tu budu?
{102918}{102948}Sledovala jsem tì.
{102991}{103040}Tohle je mùj dok... Mùj strıèek...
{103062}{103105}...Doktor Brown.
{103130}{103161}- Ahoj.|- Ahoj.
{103236}{103312}Marty. Moná, e to je trochu troufalé...
{103320}{103373}...ale pøemıšlela jsem...
{103390}{103440}...jestli bys mì nechtìl pozvat...
{103461}{103529}...v sobotu na|"Okouzlení pod moøskou hladinou"?
{103579}{103605}Chceš øíct...
{103617}{103662}Ještì tì nikdo nepozval?
{103673}{103694}- Ne.
{103723}{103752}Ještì ne.
{103788}{103865}- A co George?|- George McFly?
{103929}{104023}Je celkem milı, ale ne...
{104048}{104070}No...
{104092}{104143}Myslím, e mu by mìl bıt silnı...
{104192}{104243}...nebát se a bıt schopnı...
{104272}{104327}...ochránit enu, kterou miluje.
{104439}{104464}Nemyslíš?
{104506}{104527}Ano.
{104553}{104597}Stále tomu nerozumím.
{104603}{104666}Jak s ní mám jít na tanec...
{104670}{104734}...kdy u jde s tebou?
{104739}{104801}No, protoe, Georgi,|ona chce jít vlastnì s tebou.
{104804}{104848}Jen to ještì neví.
{104853}{104922}Proto jí musíme ukázat, e ty,|George McFly, jsi bojovník.
{104927}{105005}e si dokáeš stát za svım|a e ji dokáeš ochránit.
{105013}{105085}Dobøe, ale já jsem ještì nikdy|v ivotì nezaèal rvaèku.
{105092}{105154}Poslouchej, ty nezaèneš ádnou rvaèku, tati...
{105160}{105199}tati-tati-tamati.
{105215}{105265}Ty ji pøijdeš zachránit, jasnı?
{105270}{105340}Projdeme si ten plán od zaèátku.|20:55, kde budeš v tom èase?
{105345}{105381}Budu tancovat.
{105386}{105455}- A kde budu já?|- Budeš v autì, s ní.
{105463}{105529}Pøesnì ve 21:00,|bude na mnì moc naštvaná.
{105536}{105591}Proè by mìla bıt naštvaná?
{105595}{105701}Protoe, Georgi, slušná dìvèata se naštvou,|kdy se jim kluci snaí dostat...
{105762}{105867}- Ty se jí chceš dostat...|-Ne. Ne, Georgi, podívej.
{105891}{105936}Je to jen hra, jasnı?
{105944}{106029}Take, 21:00, procházíš se po parkovišti.
{106039}{106117}Vidíš jak zápasíme v autì.
{106125}{106198}Pøistoupíš, otevøeš dveøe|a øekneš...
{106241}{106277}Svoji vìtu, Georgi.
{106356}{106423}Hej, ty, dej od ní ty|špinavé pracky pryè!
{106480}{106537}- Opravdu si myslíš, e bych mìl nadávat?|- Rozhodnì.
{106541}{106579}K èertu, Georgi, nadávej.
{106581}{106650}Ok. Teï jsi ty na øadì.|Vrazíš mi jednu do bøicha.
{106654}{106699}Já to u mám pøipravené, e?
{106705}{106778}A ty a Lorraine ijete|spolu šastnì navìky.
{106785}{106835}Kdy to øíkáš,|zní to tak jednoduše.
{106840}{106904}Jen si pøeji...|abych nemìl takovı strach.
{106909}{106992}Nemusíš se nièeho bát.|Chce to jen trochu sebedùvìry.
{106997}{107052}Pokud do toho dáš všechno, mùeš...
{107063}{107110}...dosáhnout èehokoliv.
{107153}{107213}Poèasí v Hill Valley|tuto sobotu v noci.
{107217}{107280}Pøevánì jasno, s malou|rozptılenou oblaèností.
{107287}{107329}Teplota v noci, do dvaceti stupòù.
{107334}{107394}Jsi si jistı tou bouøkou?
{107400}{107499}Od kdy dokáí meteorologové pøedpovìdìt|poèasí, nehovoøíc o budoucnosti!
{107504}{107567}Víš, Marty, bude mi velmi|smutno vidìt tì odcházet.
{107572}{107654}Zmìnil jsi mùj ivot, dal jsi mi|cíl, za kterım mùu jít.
{107660}{107755}Jen vìdìt, e tu ještì stále|budu v roce 1985.
{107764}{107806}e v tomhle uspìju!
{107810}{107879}e budu mít monost|cestovat v èase!
{108028}{108089}Bude tìké èekat 30 rokù, ne|si s tebou budu moci zase povyprávìt...
{108093}{108160}...o tom všem, co se v posledních dnech stalo.
{108166}{108222}Budeš mi chybìt, Marty.
{108261}{108294}Vy mi budete také chybìt.
{108410}{108477}- Doktore, v budoucnosti...|- Ne!
{108480}{108602}Dohodli jsme se, e informace o budoucnosti|mohou bıt velmi nebezpeèné.
{108610}{108701}I kdy jsou tvoje zámìry dobré,|mùe to špatnì dopadnout.
{108725}{108826}Cokoliv mi chceš øíct,|zjistím to pøirozenou cestou.
{108854}{108900}"Milı Dr. Browne:
{108919}{108985}"V noci, kdy se vrátím v èase...
{108990}{109042}"...budete...
{109045}{109122}"...zastøelenı skupinou teroristù.
{109127}{109230}"Prosím, udìlejte všechny potøebné opatøení,|abyste tomuto hroznému neštìstí zabránil.
{109280}{109320}"Váš pøítel...
{109342}{109377}"...Marty."
{109516}{109586}Neotevírat pøed rokem 1985
{109604}{109670}'Dobrı veèer, Dr. Browne.|Co je s tím drátem?'
{109677}{109743}Jen malı experiment|s poèasím.
{109781}{109838}- Co máte pod tímhle?|- Ne! Nedotıkejte se!
{109842}{109905}To je speciální nové vybavení|na snímaní poèasí.
{109912}{109964}Máte na to povolení?
{109974}{110012}Samozøejmì.
{110176}{110242}- Malı moment.|Podívám se, zda ho najdu.
{111502}{111553}Vadilo by ti, kdyby...
{111555}{111616}...jsme tu ještì posedìli?
{111641}{111711}To je vıbornı nápad.|Velmi ráda.
{111716}{111825}U mám skoro 18.|U jsem takhle parkovala i pøedtím.
{111849}{111881}Prosím?
{111892}{111961}Marty, jsi nìjakı nervózní.|Je nìco v nepoøádku?
{111967}{111992}Ne.
{112018}{112044}Ne.
{112154}{112212}Lorraine, co to dìláš?
{112228}{112280}Sebrala jsem to mé|mámì z rodinného baru.
{112287}{112351}Dobøe, ale nemìla bys pít.
{112359}{112403}- Proè ne?|- Protoe...
{112422}{112504}bys toho mohla pozdìji|v ivote litovat.
{112510}{112556}Marty, nebuï takovı suchar.
{112562}{112625}Kadı, kdo nìco znamená, pije.
{112736}{112778}Jeiši, ty taky kouøíš?
{112813}{112879}Zaèínáš mluvit jako moje matka.
{113154}{113236}Dáme si teï malou pauzu,|ale za chvilku jsme zpìt...
{113242}{113303}...tak nikam nechoïte.
{113684}{113759}Marty? Proè jsi takovı nervózní?
{113792}{113820}Lorraine...
{113848}{113892}...u jsi nìkdy...
{113918}{114009}...byla v situaci, kdy jsi pøesnì vìdìla|jak se musíš chovat, ale kdy...
{114014}{114087}...k tomu došlo, tak|jsi nevìdìla, jestli to dokáeš?
{114092}{114164}Myslíš jak se máš chovat|na prvním rande?
{114177}{114214}Tak nìjak.
{114217}{114293}Myslím, e vím pøesnì,|co máš na mysli.
{114311}{114340}Vánì?
{114352}{114414}Víš, co já dìlám v takovıch situacích?
{114418}{114470}- Co?|- Nebojím se.
{114901}{114944}Tady nìco nesedí.
{114949}{115002}Nevím, co to je...
{115030}{115117}...ale kdy tì políbím, je to|jako bych políbila...
{115156}{115189}...svého bratra.
{115198}{115260}To asi nedává smysl, e?
{115264}{115302}Vìø mi...
{115324}{115364}...to dává dokonalı smysl.
{115398}{115419}Nìkdo pøichází.
{115538}{115631}Mám kvùli tobì na autì škodu|300 dolarù, ty hajzle...
{115642}{115695}...a dneska si je vyberu i s úroky,|z tvé prdele.
{115701}{115737}Dr ho.
{115739}{115802}Pus ho, Biffe. Jsi opilı.
{115820}{115872}Ale, ale, podívejme se, koho tady máme.
{115948}{116029}Ne! Zùstaò tady se mnou.|No tak, Lorraine.
{116037}{116087}Pus mì!|- Nech ji!
{116092}{116138}Seberte ho dozadu. Hned pøijdu.
{116142}{116212}Pøiznej si, e to chceš. No tak.
{116217}{116277}Zmizte.|Tohle není ádná peep show.
{116435}{116489}- Hoïme ho tam dovnitø.|- Jasnì!
{116529}{116584}Kvùli tobì jsem si musel umıvat vlasy.
{116589}{116637}Co to dìláš s mım autem?
{116640}{116706}Hej, zmiz, negøe.|Tohle se tì netıká.
{116762}{116829}Kdo je u tebe negr, ty hajzle?
{116859}{116894}- Poslouchejte, páni...
{116899}{116961}...já si nechci zaèínat|s nìjakımi feáky, dobøe?
{116964}{117005}- Bì domù k mamince pod sukni,|chlapeèku.
{117011}{117062}- Biffe!|- Nech toho, Biffe!
{117077}{117124}- Puste mì ven!
{117164}{117202}Reginalde, kde máš svoje klíèe?
{117204}{117254}- Klíèe jsou v kufru.
{117265}{117336}- Øekni to ještì jednou!|- Povídal jsem, e klíèe jsou tady uvnitø.
{117453}{117492}Pus mì!
{117667}{117692}- No tak!
{117748}{117829}Hej, ty, dej ty špinavé|pracky od ní...
{117892}{117942}Myslím, e sis spletl auto, McFlyi.
{117986}{118031}Georgi, pomo mi! Prosím!
{118037}{118119}Jednoduše se otoè|a odpochoduj, McFlyi.
{118129}{118179}Prosím, Georgi.|- Jsi hluchı?
{118185}{118230}Zavøi dveøe a vypadni.
{118297}{118379}Ne, Biffe. Nech ji na pokoji.
{118401}{118442}Dobøe, McFlyi.
{118522}{118567}Øíkal sis o to...
{118574}{118620}...a taky to i dostaneš.
{118652}{118679}Pøestaò!
{118702}{118745}Biffe, zlomíš mu ruku!
{118792}{118837}- Biffe, ne!
{118842}{118887}- Pomo mì s tím, Reginalde.
{118929}{118979}Do prèic! Poøezal jsem si ruku!
{118985}{119019}- Koho sou?|- Moje.
{119024}{119067}Díky. Moc dìkuju.
{119102}{119154}Zlomíš mu ruku!
{119163}{119237}Biffe! Biffe, nech ho!
{119242}{119300}Pus ho! Pus ho!
{120090}{120135}Jsi v poøádku?
{120613}{120659}Kdo to je?
{120667}{120712}To je George McFly.
{120792}{120834}To je George McFly?
{120838}{120870}Promiòte.
{121142}{121177}Bouøka.
{121227}{121289}Musíte se tam vrátit|a dokonèit tu tancovaèku.
{121293}{121327}Podívej se na Marvinovu ruku.
{121329}{121404}Nemùu s ním hrát|a my nemùeme hrát bez nìho.
{121410}{121444}Marvine, ty musíš hrát.
{121449}{121539}Na tom tanci se poprvé políbí.|A pokud nebude hudba, nemohou tancovat.
{121544}{121630}A pokud nemohou tancovat a políbit se,|nezamilují se a já jsem minulost.
{121638}{121727}Tanec skonèil. Jedinì, e bys|znal nìkoho, kdo hraje na kytaru.
{121904}{121962}A tato písnièka je pro všechny zamilované.
{122022}{122104}Earth Angel, Earth Angel
{122135}{122186}Will you be mine
{122214}{122269}My darling dear
{122301}{122350}Georgi, nepolíbíš mì?
{122353}{122399}Nevím.
{122426}{122480}Zmiz, McFlyi. Teï to pøebírám já.
{122644}{122717}Earth Angel, Earth Angel
{122745}{122797}The one I adore
{122801}{122842}Hej, jsi v poøádku?
{122876}{122910}Nemùu hrát.
{122914}{122943}Georgi!
{123364}{123389}Georgi!
{123418}{123448}Georgi.
{123524}{123561}Dovolíš?
{123769}{123837}The vision of your happiness
{123901}{123969}Earth Angel, Earth Angel
{123992}{124047}Please be mine
{124079}{124127}My darling dear
{124138}{124185}Love you for all time
{124229}{124285}I'm just a fool
{124336}{124389}A fool in love
{124440}{124513}with you
{124687}{124776}Paráda, to bylo dobré.|Zahrajeme další.
{124779}{124826}Ne. U musím jít.
{124829}{124902}Ještì jednu.|Zahrajeme nìco, co nahaví.
{124917}{124988}Nìco, co nahaví.
{125113}{125162}Dobøe.|- Dobøe!
{125260}{125290}Dobøe.
{125314}{125392}Tak a teï jedna 'stará klasika', ale ...
{125444}{125529}No, tam odkud pocházím,|je to 'stará klasika'.
{125574}{125627}Tak, poslouchejte, tohle je blues v B.
{125629}{125700}Sledujte mì a snate se|pøidat, dobøe?
{126110}{126178}Way down in Louisiana|Down in New Orleans
{126184}{126253}Way back up in the woods|among the evergreens
{126259}{126319}There stood a log cabin|made of earth and wood
{126325}{126385}Where lived a country boy|name of Johnny B. Goode
{126389}{126443}He never ever learned|to read or write so well
{126449}{126512}He could play the guitar|just like he's ringin' a bell
{126515}{126606}Go go|Go Johnny go, go
{126624}{126684}Go Johnny, go, go, go
{126693}{126731}Go Johnny go, go
{126736}{126790}Georgi, zaslechl jsem, e si sloil Biffa.|Jen tak dál.
{126795}{126848}Neuvaoval jsi o kandidovaní|na pøedsedu tøídy?
{126852}{126906}Johnny B. Goode
{126967}{127020}Go Johnny go, go
{127031}{127094}Go Johnny go, go, go
{127098}{127161}Go Johnny go, go
{127165}{127230}Go Johnny go, go, go
{127251}{127295}Johnny B. Goode
{127355}{127420}Chucku! Chucku, tady je Marvin.
{127426}{127485}Tvùj bratranec, Marvin Berry.
{127489}{127552}Pamatuješ ten novı zvuk,|kterı stále hledáš?
{127556}{127604}Tak si poslechni tohle.
{129269}{129328}Zdá se, e ještì nejste|na to pøipravení...
{129367}{129413}...ale vaše dìti to budou milovat.
{129515}{129543}Lorraine.
{129550}{129612}Marty, to byla zajímavá hudba.
{129630}{129661}To byla.
{129664}{129747}Doufám, e ti to nebude vadit, ale|George mì chce odvézt domù.
{129752}{129860}Vıbornì! Dobøe. Dobøe, Lorraine.|Vdy jsme z vás mìl ten správnı pocit.
{129874}{129910}Ja ho mám taky.
{129929}{129973}Poslouchejte, u musím jít, ale...
{129977}{130074}...chci vám øíct, e|to bylo velmi pouèné.
{130102}{130153}- Marty, uvidíme tì ještì nìkdy?
{130192}{130218}Za to ruèím.
{130223}{130300}Take, Marty, dìkujeme za|všechny dobré rady.
{130304}{130363}Nikdy ti to nezapomeneme.
{130379}{130415}Pøesnì tak, Georgi.
{130450}{130529}Tak hodnì štìstí.
{130629}{130672}A ještì nìco.
{130676}{130722}Jestli budete mít spolu dìti...
{130726}{130779}...a jedno z nich, kdy bude mít osm rokù...
{130786}{130854}...náhodou podpálí koberec|v obıvacím pokoji...
{130891}{130947}...nebuïte na nìho pøísní.
{130953}{130982}Ok.
{131101}{131175}Marty. Jaké pìkné jméno.
{131312}{131355}K èertu! Kde je ten chlapec?
{131440}{131468}K èertu!
{131529}{131562}K èertu! K èertu!
{131750}{131816}- Jdeš pozdì!|Nemáš smysl pro pøesnost?
{131821}{131876}Hej, no tak. Musel jsem se pøevléct.
{131880}{131946}Nemùu jít pøeci spát v tom|potápìèském obleku.
{131952}{132012}Ten mùj otec to fakt dokázal.|Vyšlo to.
{132018}{132066}Sloil Biffa jednou ranou.
{132070}{132163}Nevìdìl jsem, e to má v sobì.|Nikdy v ivotì se Biffovi nevzepøel.
{132207}{132287}-Nikdy?|-Ne. Proè? Co se dìje?
{132305}{132335}Dobøe!
{132343}{132392}Nastavme cílovı èas.
{132509}{132562}- Toto je pøesnı èas,|kdy jsi odešel.
{132574}{132653}Pošleme tì zpìt pøesnì do|momentu, kdy jsi odešel.
{132727}{132774}Jako bys nikdy neodešel.
{132821}{132920}Tak, nìkde tam vzadu jsem nakreslil|na cestu bílou èáru.
{132929}{132972}Odtud odstartuješ.
{132976}{133028}Zmìøil jsem pøesnì vzdálenost...
{133032}{133095}...vzal jsem do úvahy|zrychlení vozidla...
{133100}{133197}...a odpor vìtru zpìtnì od|momentu, kdy udeøí blesk...
{133208}{133313}...co bude pøesnì za 7 minut a 22 sekund.
{133324}{133381}Kdy zazvoní budík, šlápneš na plyn.
{133386}{133413}Dobøe.
{133573}{133647}Tak, myslím, e to je všechno.
{133748}{133804}- Díky.|- Dìkuji.
{133935}{133980}- Uvidíme se za 30 let.
{134024}{134063}Doufám, e jo.
{134098}{134135}Neboj se!
{134150}{134191}Pokud se ti podaøí kontakt s kabelem...
{134195}{134266}...pomocí kontaktního háku|v rychlosti 88 mil za hodinu...
{134271}{134337}...pøesnì v momentu, kdy zasáhne blesk vì...
{134399}{134449}...všechno bude fajn.|- Správnì.
{134671}{134756}- Co má tohle znamenat?|-To zjistíte za 30 let.
{134762}{134809}Je to o budoucnosti, e?
{134814}{134876}- Informace o budoucnosti.|- Poèkejte chvíli.
{134881}{134926}Varoval jsem tì, chlapèe.
{134930}{134994}Následky by mohli bıt katastrofální!
{135000}{135055}Doktore, to je riziko, které|musíte podstoupit.
{135059}{135133}- Závisí na tom váš ivot!|- Ne!
{135138}{135215}Odmítám pøevzít zodpovìdnost.
{135226}{135287}V tom pøípadì vám to povím pøímo.
{135388}{135420}Ksakru!
{135612}{135682}Seber ten kabel, já|ti shora shodím lano.
{135687}{135736}- Jasnì! Rozumím!
{136548}{136578}Doktore!
{136763}{136857}- Rychle, rychle. Jdeme na to!|- Dobøe! Vytáhnìte to nahoru!
{136943}{136968}Pojïme!
{137139}{137163}Doktore!
{137194}{137275}Musím vám povìdìt o budoucnosti.
{137280}{137378}- Co?|- Musím vám povìdìt o budoucnosti!
{137387}{137418}Co?
{137421}{137529}V noci, kdy se vrátím zpìt v èase, budete...
{137621}{137651}Doktore!
{137875}{137896}Bì!
{137921}{137973}- Ne, Doktore!|- Podívej se na èas!
{137983}{138032}Máš necelé ètyøi minuty.
{138037}{138076}Prosím, pospìš si!
{138356}{138387}- Ano!
{139665}{139740}Sakra, Doktore!|Proè jste jen musel roztrhat ten dopis?
{139746}{139791}Kdybych jen mìl víc èasu.
{139865}{139919}Poèkat.|Mám èasu kolik chci.
{139923}{140006}Mám pøeci stroj èasu. Mùu|jednoduše pøijít døív a varovat ho.
{140012}{140061}Ok. Deset minut by mìlo staèit.
{140110}{140162}Ok. Èasovı okruh zapnutı.
{140173}{140234}Proudovı kondenzátor, proudí.
{140248}{140296}Motor bìí. Pøipravenı.
{140366}{140421}Ne. Ne, ne.
{140426}{140503}Pojï. No tak. Ne teï.
{142193}{142223}- Pojï.
{142275}{142338}A jdeme. Jdeme.|Ještì jednou. No tak.
{142381}{142447}Prosím. Prosím. Naskoè!
{144807}{144839}Doktore.
{147148}{147196}Šílenı oralı øidiè.
{147558}{147605}V poøádku. Frede.
{147652}{147714}Vypadáš úasnì. Všechno vypadá vıbornì.
{147750}{147773}1:24.
{147777}{147843}Stále mám èas. U jdu, Doktore!
{147932}{147987}Ne! Ne znovu!
{147992}{148049}No tak! Naskoè!
{148378}{148410}Libíjci.
{148952}{148976}Ne!
{149009}{149040}Bastardi!
{149365}{149395}Za ním!
{150221}{150271}- Doktore! Doktore!
{150441}{150462}Ne!
{150813}{150847}Vy jste ivı.
{151071}{151106}Neprùstøelná vesta?
{151141}{151186}Jak jste to vìdìl?
{151199}{151261}Nemìl jsem monost|vám to øíct.
{151584}{151676}A co všechny ty øeèi|o míchání se do budoucích událostí?
{151683}{151728}Èaso-prostorové kontinuum?
{151743}{151809}No, uvìdomil jsem si...|k èertu s tím.
{152058}{152101}- Tak jak daleko do budoucnosti jedete?
{152105}{152176}Tak 30 rokù. Je to pìknì kulaté èíslo.
{152181}{152230}Navštivte mì, kdy tam budete, dobøe?
{152235}{152283}Budu mít tak okolo 47.
{152291}{152316}Navštívím.
{152330}{152355}- Dávejte na sebe pozor.
{152384}{152408}I ty.
{152414}{152467}Správnì. Mìj se, Einie.
{152481}{152547}- A pozor na ten skok zpìt.|Trochu to tøese.
{152570}{152593}Samozøejmì.
{154160}{154193}Jakı strašnı sen.
{154463}{154539}- Jestli bude volat Paul, povìz mu,|e budu dnes pracovat v butiku déle.
{154544}{154592}Lindo, nejsem tvùj záznamník...
{154596}{154677}...a nìkdo se jménem Greg nebo Craig|ti u pøed chvilkou volal.
{154683}{154776}- A kterı to tedy byl?|- Nestíhám sledovat všechny tvé pøítele.
{154841}{154878}- Co to k èertu je?
{154899}{154925}Snídanì.
{154938}{154990}- Zase jsi spal obleèenı?
{154999}{155027}Ano. Mìl...
{155056}{155110}Co to máš na sobì, Dave?
{155122}{155147}Marty...
{155161}{155212}...vdy chodím do práce v obleku.
{155231}{155271}- Jsi v poøádku?|- Jasnì.
{155295}{155345}- Musíme si dát odvetu.|- Odvetu?
{155349}{155399}- Proè? Podvádìla jsi?|- Ne.
{155403}{155443}- Ahoj.|- Dobré ráno.
{155497}{155532}Mami! Tati!
{155543}{155601}- Bouchl jsi se do hlavy?|- Jsi v poøádku?
{155606}{155678}Vypadáte úasnì.|Mami, jsi tak štíhlá.
{155688}{155745}No, dìkuji, Marty. Georgi!
{155784}{155824}Dobré ráno, spáèi.
{155856}{155919}- Dobré ráno, dìcka.|- Ranko.
{155925}{155983}- Marty, skoro jsem zapomnìla.|Jennifer Parkerová ti volala.
{155987}{156070}Moc se mi líbí, zlaté dìvèe.
{156086}{156135}Nemáte dnes to velké rande?
{156139}{156181}Co? Co, mami?
{156185}{156277}Nejedete dnes k jezeru?|Plánovali jste to pøeci dva tıdny.
{156286}{156344}U jsme to pøeci probírali.|Jak mùu jít k jezeru?
{156352}{156378}Kdy auto je na šrot.
{156381}{156416}- Na šrot?|- Na šrot?
{156422}{156472}Kdy se to stalo?|Proè mi to nikdo neøekl?
{156476}{156559}- Jsem si jistı, e auto je v poøádku.|- Proè se o tom dozvídám poslední?
{156570}{156636}- Vidíš? Biff ho tam venku právì voskuje.
{156655}{156755}Tak, Biffe, chci se jen ubezpeèit, e|tam budou dvì vrstvy vosku, ne jen jedna.
{156761}{156856}- Právì dokonèuju druhou.|- Biffe, nesna se mì oblafnout.
{156900}{156944}Promiòte, pane McFlyi.
{156950}{157016}Chtìl jsem øíct, e právì|zaèínám druhou vrstvu.
{157036}{157087}Biff. To je pøípad.
{157094}{157149}Stále se chce z nìèeho ulít.
{157154}{157223}Musím na nìho dohlíet|u od støední.
{157228}{157321}- Ale kdyby nebylo jeho...|- Nikdy by jsme se nezamilovali.
{157368}{157427}Pane McFlyi! Pane McFlyi, tohle právì pøišlo.
{157433}{157494}Ahoj, Marty.|Myslím, e je to vaše nová kniha.
{157564}{157618}Miláèku! Tvoje první novela.
{157657}{157774}Vdy jsem ti øíkal, kdy dáš do toho všechno,|mùeš dosáhnout èehokoliv.
{157783}{157866}Marty, to jsou tvoje klíèe.|Je celé navoskované, pøipravené na veèer.
{157876}{157898}Klíèe?
{158295}{158351}- Tak co bude s tou jízdou, pane?|- Jennifer!
{158394}{158439}Tak rád tì vidím.
{158449}{158489}- Uka se mi.
{158502}{158568}Marty, chováš se jako bys mì|celı tıden nevidìl.
{158573}{158599}Vdy je to pravda.
{158621}{158647}Jsi v poøádku?
{158669}{158711}Je všechno v poøádku?
{158779}{158804}- Jasnì.
{158859}{158897}Všechno je super.
{159244}{159266}Marty!
{159300}{159347}Musíš se se mnou vrátit!
{159365}{159417}- Kam?|- Zpìt do budoucnosti.
{159533}{159575}Co to dìláte, Doktore?
{159610}{159638}Potøebuji palivo.
{159718}{159767}Rychle! Nastup do auta.
{159777}{159880}Ne, ne. Právì jsem se vrátil. Je tu Jennifer.|Jdeme se svézt v novém autì.
{159887}{159953}- Tak jí vezmi s námi.|Tohle se tıká i jí.
{159959}{160039}O èem to mluvíte?|Co se nám stane v budoucnosti?
{160050}{160118}- Stanou se z nás idioti nebo co?|- Ne, Marty.
{160123}{160200}Oba, ty i Jennifer, budete fajn.|Jde o vaše dìti, Marty.
{160205}{160256}Musíme nìco udìlat pro|vaše dìti.
{160411}{160481}Mìli bychom ješte couvnout. Cesta není|dost dlouhá, abychom dosáhli rychlosti 88 mil.
{160487}{160558}Cesty? Tam, kam my jedeme,|nepotøebujeme cesty.
{160633}{160783}RELEASED BY xCZ-2oo2|***ENJOY OUR RELEASES***
